### ISSUE TITLE
Add version browsing components

### ISSUE THREAD

**Issue by twostoryrobotrange** [bcgov/range-web#122]
We are going to add some form of versioning to the application. We've decided that some version browsing components are necessary for selecting previous versions of the RUP.

Create components to display a list of previous versions for a given RUP.

![image](https://user-images.githubusercontent.com/50648653/64568968-62fe8000-d319-11e9-940b-25aa26bd9562.png)

The designs are fairly rough, but the technical requirements are fairly clear:

* display a list of previous versions
* highlight approved previous versions
* collapse all other status of previous versions

**Comment by LisaMoore1** [comment]
@calebissharp To test this what workflows are related and what should I be looking for? The three bullets in the description? Basically I'm trying to figure out the definition of done for this one so I can test appropriately. I'm guessing that in addition to any key things I should see that are different I'll need to test all main workflows to look for any unexpected consequences. Thanks.

**Comment by calebissharp** [comment]
@LisaMoore1 I guess there isn't anything specific to test. I added the label to let you know that the versioning changes have been merged in. There is the "view versions" page that could be tested though, just to see if there's any bugs. This issue can probably be closed though, since the version browsing components have been implemented.

**Comment by LisaMoore1** [comment]
@calebissharp RAN099912 and RAN099953 both have multiple rows showing in the work queue but the view versions screen indicates there are not any other versions.  
I'm wondering if it is because in both the RANs above the "2nd" version is in progress somehow (not at an approved status). 
What triggers there being other versions? Is there an example I can look at?

**Comment by LisaMoore1** [comment]
@calebissharp The comment above is more a question than an unresolved but I thought it would be good for me to understand it before I close.  Thanks.

**Comment by calebissharp** [comment]
@LisaMoore1 I think that's a remnant of the old "versioning" system the previous developers were starting to implement, where they were duplicating RUPs. In the new system, you'll be able to view new versions in a separate "version" page, and there will only be one plan that shows up in the list page (the current version of the plan). We'll have some kind of migration for these pseudo-versioned plans.

**Comment by LisaMoore1** [comment]
@calebissharp What will happen when there is an approved RUP (should always be visible) and an amendment is in progress (which they will need to be able to see/access easily to proceed to approved)? I'm closing this issue but something to consider as you plan moving forward.
