### ISSUE TITLE
Pasture | Allowable AUMs field error when new pasture created prevents saving draft

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#134]
Immediately generated an error coloured field when pasture created (must think a number is REQUIRED)
Default (acceptable) needs to be blank (not a number)
Message is: pastures[1].allowableAum must be a 'number' type, but the final value was: 'NaN' (cast from the value'""'
Default to blank (no value) and text on screen "Not set"

**Comment by micheal-w-wells** [comment]
@LisaMoore1 we are changing our workflow so that issues wont get closed when we merge code in.   Once we get zenhub working we can move them to a test column and then you can close them if they look good (thanks @calebissharp for your suggestion).

This one is ready for you to move in to your test column : )
