### ISSUE TITLE
When no action has been selected yet the field is showing the top action of the dropdown list

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#164]
Right now in staff view the top option of the drop down list for the fields below is displayed in grey. It isn't clear that you can:
1) select from the list
2) type to filter the list
3) type something other than on the list for "other"

Default text (visible until field has been entered) should be something like "Type or select"
**Related Fields**
- Actions (Plant Communities)
- Indicator Species - Readiness
- Indicator Species - Stubble Height

**Comment by LisaMoore1** [comment]
![F4C6EE63-C2B9-43BD-B589-AAC4A9ED2FD5.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/90598a8d-1d51-402e-b248-ca5fbda5ae0f)

**Comment by calebissharp** [comment]
This issue is caused by a bug in the semantic-ui Dropdown component: https://github.com/Semantic-Org/Semantic-UI-React/issues/3130. They say this is intended behaviour, so the chances of it being fixed are fairly low.

There is currently no workaround without disabling the select on blur functionality (ie. it won't select the option on tab)

**Comment by LisaMoore1** [comment]
@calebissharp Can we an info popup (ex. little question mark is what we used on iPad) or text beside the field (if room) that indicates they can do the three things mentioned in the description for this issue?

**Comment by LisaMoore1** [comment]
@calebissharp Relted to #175

**Comment by LisaMoore1** [comment]
Closing this one as our chosen solution was the info option.
