### ISSUE TITLE
Default values for readiness criteria and height after grazing for stubble height is not showing -- should be to one decimal

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#178]

**Comment by calebissharp** [comment]
@LisaMoore1 once there issues are resolved I would recommend actually closing them to signify that.

**Comment by micheal-w-wells** [comment]
I think @LisaMoore1 is trying to keep track of what is in production via whether or not it is closed.  I think she's moved them to done in zenhub,  but we could label them 'ready for prod' if that makes more sense.

**Comment by calebissharp** [comment]
But all the changes in dev are eventually going to be in production anyway, since it's just a promotion of the branch. Regardless if it's deployed or not, once an issue is resolved, it's no longer an issue. I think tracking what changes are in prod should be a different process, eg. using releases.

**Comment by micheal-w-wells** [comment]
I hear you.  I opted to go this route for now because it makes it very easy for non devs to see which issue fixes and changes have made it in to the field.  I'm flexible on how stuff gets tracked on here we just have to teach Lisa how to easily see what is in the field or not, be it releases or whatever.

**Comment by LisaMoore1** [comment]
A few things here (I just did some learning):

- I need to move things out of sprint pipeline as I test so I can see what I've looked at
- burndown for a milestone is based on issues being closed (no burndown until they are closed)
- in general burndowns should show when within the sprint the work is being done -- over time we could identify if we have a big drop early or late --> we should be aiming for steady burndown which would be mean moving cards to closed when they pass testing but haven't necessarily been deployed to prod
- I'm OK with marking something as "closed" so long as there is certainty that those things will be moved to prod 
- ideally we are able to complete a "chunk of work" (i.e. a user story) in a sprint so that we can do a release into prod at the end of the sprint
- I'm not familiar with the deploy process but if I can have confidence that if I mark something as closed it will actually end up in prod I'm pumped to hit closed on them when they are working (that is where the fun is at)

Make sense?

**Comment by calebissharp** [comment]
@LisaMoore1 and @micheal-w-wells I think you both raise good points. My understanding of the deploy pipeline is that once we merge a change into the `dev` branch, it's going to eventually end up in production, ie. we can't pick and choose which pull requests end up in prod. Because of that, fixes for any issues are guaranteed to make it into production. The burndown graph was actually what made me realize none of the issues were closed, since it only knows an issue is resolved if it's closed. For us, closing issues when they are fixed is the ideal workflow.

How we know when to promote `dev` to `prod` I'm not sure about. I imagine it will coincide with an epic or user story being finished.

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp Since this is a grand experiment of a sprint why don't we close the ones that I've already tested (and will yet test) for this sprint and until I'm able to learn about the merging etc. and we have a more concrete release plan I will trust it will happen. Sound like a plan? 

As for releases I'm strongly in favour of releasing when  a user story is complete.

**Comment by LisaMoore1** [comment]
It's a plan. If they pass testing I'll close them. In a week or two we can see if that is working for us or not.

**Comment by calebissharp** [comment]
Sounds good!
