### ISSUE TITLE
RUP components' order should remain the same after save

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#492]
Thought at first my change didn't save, but it had actually saved and reordered the pastures, opening one that looked like my old one.  Pastures should remain in the same order after a save, and ideally what I had open is what stays open.

@LisaMoore1 fyi

Components to order:
- [ ] Pastures 
  - [ ] Plant communities
    - [ ] Indicator plants
    - [ ] Monitoring areas
    - [ ] Plant community actions
- [ ] Grazing schedules (by year)
  - [ ] Grazing schedule entries 
- [ ] Minister issues
  - [ ] Minister issue actions
- [ ] Additional requirements
- [ ] Mangement considerations

**Comment by LisaMoore1** [comment]
Noted this behaviour a s well on #457 (wasn’t sure if it was part of the bigger issue or a separate thing).  Comment was:
Note that in both browsers on iPad immediately following save action I regularly get navigated away from where I entered/deleted the indicator plants to a different pasture (at least I think that’s where I’m consistently getting navigated to).

Followed up by a qualifier that “regularly” isn’t always since sometimes I stay put.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I think we after we have critical workflows happening we could do a chunk of a sprint on updating usability/readability. There are a few issues kicking around that have to do with that (both plan and PDF). If we let it go for a bit we might get more suggestions and then we could have a “make it a pretty baby” few days.

**Comment by calebissharp** [comment]
Could sort by date created potentially to fix this.

**Comment by LisaMoore1** [comment]
@calebissharp I think sort by name is most logical. When (date/time) they are added doesn't matter --- being able to find the one you want quickly does. Alphabetical is fairly standard for that I think. 

Of concern was that sometimes the save/delete action punts me out of the pasture altogether and into a different one which is seriously confusing. I haven't noticed that behaviour since the save/delete started working but something to keep an eye open for.

**Comment by calebissharp** [comment]
If we sort by date, the order will remain the same as when you create the pasture, ie. won't shift after you save. It also means if you change the name it won't suddenly move.

**Comment by LisaMoore1** [comment]
@calebissharp I’ve put this to the SME group. Will have definite answer for you by noon tomorrow.

**Comment by LisaMoore1** [comment]
@calebissharp No particular preference one way or the other only that it is consistent in every plan. You can go ahead with order entered if that is what you prefer.

**Comment by calebissharp** [comment]
Increasing the scope of this issue to cover all components of an RUP.

**Comment by LisaMoore1** [comment]
Let me know which ones you identify as requiring “treatment” so I’m aware for testing etc?

**Comment by calebissharp** [comment]
@LisaMoore1 Yep. I've updated the issue.

**Comment by LisaMoore1** [comment]
Nearest I can figure this is working (was watching for it during all my other testing). A hard one to target test for. Am closing for now.

**Comment by LisaMoore1** [comment]
@calebissharp Noticed an order change in Minister's Issues after a submit from AH to staff for feedback

**Comment by LisaMoore1** [comment]
@calebissharp I noticed that when AH worked in issues then saved the order of the issues saved. Then when staff saved the order saved the same but after working in actions (added one) the order of the actions changed after save.  Really not sure how to capture what is going on here.  Sorry.
