### ISSUE TITLE
At least one Range Officer seeing same agreement more than once.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#510]
Still trying to replicate in test.  The duplicates are of agreements without plans so far.

@LisaMoore1 fyi

**Comment by LisaMoore1** [comment]
@micheal-w-wells I logged in to PROD with BCeID and everything appeared as it should.  All agreements reported as “missing” were assigned to user and those identified as having duplicates were only appearing once.  I’m going to send a note to the SME group requesting that they each log in to PROD using their IDIRs and identify if the RAN list looks correct and if there are any duplicates.  I will request that they report their findings to your email. That will let us know if it appears to be any broader.

**Comment by LisaMoore1** [comment]
@micheal-w-wells if you’re working on this one can you move it over to in progress and throw some sort of estimate on it? Thanks

**Comment by micheal-w-wells** [comment]
@LisaMoore1 got nothing to go on for this one yet other than report from Phil.  Spent some time trying to reproduce and no one else seems to have the problem as of yet, going to park for the moment but leave open.

**Comment by micheal-w-wells** [comment]
Tried getting him to delete cookies again, it got rid of only one of the duplicates.

**Comment by LisaMoore1** [comment]
So weird. If it got rid of one of the duplicate why isn't it getting rid of all of them? Hmm Chrome?

**Comment by micheal-w-wells** [comment]
Same version of chrome as me!

**Comment by micheal-w-wells** [comment]
moving to in progress as this should be resolved with the new home page table

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells There are some funny things happening here. I can’t really tell which a “real” and which are because my connection is so slow. I’ll list some observations here. Can you let me now which are actually related to this and which should be separate issues?
- when I first sorted by status (descending) the SDs came at the top (expected). After filtering down to Dwyer and then getting rid of that filter I can’t recreate that sort with SD at the top — or anywhere that I can find...
- Anything that hasn’t at least hit SD don’t have a staff contact showing (since I’m logged in I should be the staff contact for everything but I’m not showing up on most)

There will be others as I test more... Sorry I can’t differentiate between real issues and connection issues but that is likely the way of the next couple of weeks :)

**Comment by micheal-w-wells** [comment]
Double check Lisas duplicates in test and after this deploy check that no other staff has the issue in prod.

**Comment by ZoeSimon** [comment]
@micheal-w-wells is this the sort of duplication that you guys are referring to? I just checked my zone in prod and I still have one AH that has duplication:

![image](https://user-images.githubusercontent.com/62561887/77929067-169b7300-725e-11ea-9cf3-427e53bd6894.png)

**Comment by LisaMoore1** [comment]
@zoesimon These entries are multiple RUPs for the same RAN. I think this issue was multiple RANs. I think this is what we are referring to when looking at versions —  in test there were some that 15 or so RUPs for the same RAN.

**Comment by ZoeSimon** [comment]
@LisaMoore1 Ah okay, gotcha.

**Comment by ZoeSimon** [comment]
@micheal-w-wells Hey Mike, have we heard anything back from Phil on this one?

**Comment by micheal-w-wells** [comment]
Not since I last messaged him.  I made a note to ping him after this upcoming release as all the code related to his problem will have been changed (we think).

**Comment by micheal-w-wells** [comment]
Pinged Phil before i forgot.  Some of his dupes are gone (yay) some are still there.  I've got the RANS to follow up on.  If either @LisaMoore1 or @ZoeSimon has time to look in metabase for anything interesting related to them ping me for the RANS otherwise going to park for today and pick up at some point in time this week.

**Comment by LisaMoore1** [comment]
RANs please. I'd like to take a look.

**Comment by micheal-w-wells** [comment]
FINALLY.  See issue mentioned above.
