### ISSUE TITLE
History comments (showing status update times and comments) are not showing up in all statuses.  

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#517]
If comments between staff/AH exist they should be displayed in history.

**Comment by micheal-w-wells** [comment]
myra=# select id, plan_id, from_plan_status_id, to_plan_status_id, note from plan_status_history where plan_id
in (select id from plan where agreement_id in ('RAN099955', 'RAN099951')) order by  id asc;
 id  | plan_id | from_plan_status_id | to_plan_status_id |
             note
-----+---------+---------------------+-------------------+-----------------------------------------------------
-----------------------------------------------------------------------------------
   1 |       2 |                   1 |                 4 |
   2 |       2 |                   4 |                13 | Please take a look at my schedule and concern.
   3 |       2 |                  13 |                 5 | I’m not able to edit anything — which is what I was
trying to test. Sending back to AH and will try workflow again when I get updated
   4 |       2 |                   5 |                 1 |
   5 |       2 |                   1 |                13 | Handing off for edit testing.
  46 |       2 |                  13 |                 5 | Change
  51 |      54 |                   1 |                13 | Test if I can save/submit from staff.
  52 |      54 |                  13 |                 5 | More years added to test copying schedules.
  53 |      54 |                   5 |                13 | Test if staff can change things and then submit back
 with save
  54 |      54 |                  13 |                 5 | Added a second minister’s Issue — check if it saved
  55 |       2 |                   5 |                13 | Check if PC Action “other” is working
  56 |       2 |                  13 |                 5 | Testing Display for PC Action “other”
  57 |       2 |                   5 |                13 | Test display of other action for MI
 104 |      54 |                   5 |                13 | Checking what happens when I change status (AH)
 112 |     147 |                  13 |                19 |
 113 |     147 |                  19 |                14 | Test confirm
 114 |     151 |                  14 |                15 |
 115 |     151 |                  15 |                10 | Check if AH can edit in status 10 (not approved - ch
ange requested)
 116 |     151 |                  10 |                13 | Check save prompt for 10
 117 |     152 |                  13 |                 5 | Checking if submitting with no save saves the conten
t (schedule narrative)
 118 |     152 |                   5 |                13 | AH COmment test in narrative
 119 |     153 |                  13 |                 5 | Requesting changes and testing comment display.
(22 rows)

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp If it does display in 099955 it is only showing the most recent comment not all of them.

**Comment by calebissharp** [comment]
This looks like it's an API issue related to versioning. Closing in favour of https://github.com/bcgov/range-api/issues/123
