### ISSUE TITLE
Change error message for invalid fields on submitting to include fields at issue

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#518]
Change the error popup to better indicate what field(s) is/are a problem.

**Comment by calebissharp** [comment]
This *is* possible, and relatively straightforward to implement. This solution I would recommend over #514.

@LisaMoore1 What format would you prefer to show the field in (ie. with nested fields)?

**Comment by micheal-w-wells** [comment]
I'd lean towards something like below but Lisa's call. For the example that started #514:

Pasture 
  > Plant Community 
     > Range Readiness 
       > Other: [Error here]

If you wanted to help out the guys with lots of content in their RUP:

Pasture BIG RED 
  > Plant Community Weeds R Us 
    > Range Readiness 
      > Other: [error here]

**Comment by calebissharp** [comment]
We should probably limit the notification to show 1 error at a time then, since I can see the message easily becoming very long and unwieldy with many errors.

**Comment by LisaMoore1** [comment]
#514 is related to this one as we need to allow saving at any point so that if staff get called away (ex. front desk call) they can save what they've done without having to figure out where to add a bunch of little placeholders to get to save and then have to go back and put in "real" data when they have time. Saving easily is important!

I like one error at a time -- I fix that one and when I try to submit again I get the next one.  I don't mind so much if I'm able to save between times in case I need to step away.
