### ISSUE TITLE
Weird behaviour on attempting decimal percentage for PLD

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#573]
If you attempt to enter a fraction of a percentage say .5, it instantly rounds up to 1 and then once you navigate away it goes to 0.  I tried with 1.5, rounds to 2, then you navigate away and it goes back to 1, so I think there's the pattern.

If we aren't doing fractions lets alert/go red on someone entering a decimal if that is easier to fix, if we're supposed to round it would be cool if it notified the user rounding was happening.  If we are supposed to round then we should stop it subtracting one when leaving the field.

Open to your input @LisaMoore1

**Comment by LisaMoore1** [comment]
@micheal-w-wells Red messaging would be good re. whole number requirement. Same thing for Allowable AUMs for each pasture (that has separate issue)

**Comment by LisaMoore1** [comment]
@micheal-w-wells Red messaging would be good re. whole number requirement. Same thing for Allowable AUMs for each pasture (that has separate issue #560))

**Comment by micheal-w-wells** [comment]
Simplest thing to do here was to force whole numbers.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I’m getting the “must be whole number” message when I enter a whole number like 5 or 10. The red and message also appear immediately upon me entering any value rather than on exit field like the other field validations do. Not sure if that is a problem or if it is validating after each keystroke
