### ISSUE TITLE
In Test when editing a staff draft as range staff, the Grazing Schedule has "no options" in the Livestock Type dropdown.

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#709]
Tried to create a plan and started editing in staff draft, added a row to the Grazing Schedule and when trying to select the Livestock Type it listed "no options."

![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/a4ea41a6-e657-45b5-b61f-d80605f24050)

![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/8ba1eea9-293f-4bcd-aa6b-498b822c7378)

**Comment by LisaMoore1** [comment]
@micheal-w-wells and @calebissharp @zoesimon Something interesting I can’t explain that happened this morning:

- In RAN099954 (AH add content to original) I tried to add schedule and livestock type was “no options”
- I went to RAN099953  version snapshot showed “not provided” even though I know they had been cow/calf on March 27th since I entered them
- I went to RAN099953 V4 and created a PDF — looked right
- I returned to RAN099954 and I now have options to add livestock type and all versions all plans are showing the livestock type previously selected

**Some screenshots**
![7778FD5A-424B-4AEC-B90E-463DB6C808DB.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/504dfdd8-48d8-45d7-9469-5189dfb71cc0)
![1D4D8AA5-3C76-4878-9A9D-A3BFAB2008ED.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/e3dfe46b-a532-467b-b57e-b6c927a42621)
![C4D0195B-4CDF-4795-9BB0-575A797A2A0A.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/997b42c4-064d-4d43-93de-339e91016c1f)

**Comment by LisaMoore1** [comment]
This feels like something we need to address before release (if we don’t we’re introducing an error into PROD). @micheal-w-wells Would that be accurate? If so it should be added to the epic for this deploy.
