### ISSUE TITLE
Create file attachment list

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#848]
**Describe the task**
Expand on [previous U](https://github.com/bcgov/range-web/pull/421)I for file attachments. We need to take what Kaileen had originally started and make it work for recommendation packages, maps etc. It needs to work with API endpoint reference bcgov/range-api#217. 

**To do for @LisaMoore1 **
- [ ] Who should be able to attached what and where
- [ ] Who should be able to see it

**Acceptance Criteria**
- [ ] TBD

**Additional context**
- TBD

**Comment by LisaMoore1** [comment]
In each category there could be more than one attachment
When minor amendments are made if a map is added it must automatically be attached to the new version(s) — the current legal version must always show a map (if there is one)
When a mandatory amendment occurs the past attachments should not automatically move forward — staff must identify (confirm) map and other attachments to include — i.e. when a DM needs to make a decision the staff person needs to consider what additional or updated info is associated with that decision

**CATEGORIES (I think)**
Map
- uploaded by staff
- visible to staff/Decision Maker and AH (all)

Consultation/referral Information
- uploaded by staff
- visible to staff/decision maker 

Other
- uploaded by staff
- option to “describe” (indicate type) of file
- select visibility options (from staff/decision maker, AH, future viewers like C&E/referring agencies)

**Comment by okanji** [comment]
@LisaMoore1 re your noes on the different categories, it seems to me like only staff should be able to upload attachments. Is this correct?

**Comment by LisaMoore1** [comment]
Yes.  Staff can upload attachments for sure.

**Comment by okanji** [comment]
> Yes. Staff can upload attachments for sure.

Sounds good. Should Agreement holders be able to upload as well?

**Comment by LisaMoore1** [comment]
If I remember correctly for this basic version we were going with just staff. @micheal-w-wells might know better.  We can get by with just staff for now provided that DMs are able to submit comments in a field that then is visible in a section of the RUP.

**Comment by okanji** [comment]
Okay sounds good @LisaMoore1 thanks for the clarification

**Comment by micheal-w-wells** [comment]
Let's just do staff, but there should be a toggle for whether or not the attachment is one that should be visible for staff vs AH.

**Comment by okanji** [comment]
This is what I have for the categories. @LisaMoore1 @micheal-w-wells what do you think about this? @LisaMoore1 do we have a solid idea about what the categories should be (if not we can always add/ change categories in the future).

![image](https://user-images.githubusercontent.com/30703259/86957710-f6f2d100-c10f-11ea-8c76-327aeb7a5d51.png)

@micheal-w-wells  I will add the toggle for whether or not the attachment should be visible for AH.

**Comment by LisaMoore1** [comment]
I think our most likely attachment type is decision recommendation which could consist of things like:
- recommendation summary
- consultation record
- potentially referral info from some other agency like parks/stewardship

Since consultation information is one aspect of the larger “decision materials” category I wonder if it might work to have the categories something like
- map attachment
- decision materials
- other

Also just thinking that once a plan is approved the option to add attachments should no longer be available until an amendment is started. 
In a more complicated version (not for right now? @micheal-w-wells?) we’d want to 
- hold on to the map for amendment version(s) (will need an option to replace it to add something more current though — for example the mandatory amendment could be associated with a boundary change)
- not include the decision materials or other attachments with the new amend version(s)
- we need to make sure that we don’t create a situation where an attachment that is important to a specific version gets removed from a future version and then also becomes “disassociated” with the previous version(s)
- I don’t remember the data structure for attachments but I think they are at the agreement level — worth some revisiting at a later date I think. For now, the above looks good if we can decide on categories.

**Comment by LisaMoore1** [comment]
@calebissharp @okanji Trying to test this morning.  Have noticed that when after an agreement holder has signed attachments can no longer be added.  We need to be able to add decision materials at that time (in fact that IS the time when he decision materials get added). 
- Ideally only “decision materials” attachments would be possible at this time — not sure if the attachment options can be divided in that way
- if allowing only certain types of attachments at this status is not a possibility please change so that all attachments are possible at all statuses except:
   - minor amendment stands statuses — with the exception of the one where staff are making a recommendation to the DM to review it for wrongly made determination (I’m not sure what status that one is) 
   - approved/not approved statuses (after something is in effect)

**Comment by calebissharp** [comment]
@LisaMoore1 Do you think we can just blanket allow staff to attach files in any status?

**Comment by LisaMoore1** [comment]
Legally we can’t allow content changes to something that the AH has already signed.  The map is considered content. All the statuses up to confirmed by AH should allow attachments (original plan and amendments). Once AH has signed staff need to be able to attach decision materials — that’s the tricky one I think.  It’s really the map that needs to be locked down in the statuses that “follow” AH signature.  Not sure if that helps any....

Lisa Moore P.Ag.
Sent from my iPad

On Jul 29, 2020, at 10:48 AM, Caleb Sharp <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@LisaMoore1<https://github.com/LisaMoore1> Do you think we can just blanket allow staff to attach files in any status?

**Comment by calebissharp** [comment]
@LisaMoore1 Gotcha. It helps us to know what we can get away with for making the implementation easier, ya. 

@okanji I think what we do here is wrap the `Attachments` component (or maybe all of the attachment components in `PlanForm`) in another `EditableProvider`. We then create another function that looks like `canUserAddAttachment = (user, plan) => bool` and pass that to the `editable` prop of the provider. It will basically be the same as the `canUserEditThisPlan` function, but with more statuses (I think). This will work since that provider will be closer in the tree to the attachments component and will override the provider that's making everything else not editable.

**Comment by calebissharp** [comment]
@okanji I'm going to implement this because it sounds like you're busy with the conditions stuff.

**Comment by okanji** [comment]
@calebissharp sounds good thanks

**Comment by calebissharp** [comment]
@LisaMoore1 Ready to go again, Range Officers should be able to add attachments in the right statuses.
